spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wheel_car
    username: postgres
    password: Chhinghor7944!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
